INSERT INTO BRAND (name) VALUES ('A');
INSERT INTO BRAND (name) VALUES ('B');
INSERT INTO BRAND (name) VALUES ('C');
INSERT INTO BRAND (name) VALUES ('D');
INSERT INTO BRAND (name) VALUES ('E');
INSERT INTO BRAND (name) VALUES ('F');
INSERT INTO BRAND (name) VALUES ('G');
INSERT INTO BRAND (name) VALUES ('H');
INSERT INTO BRAND (name) VALUES ('I');

INSERT INTO CATEGORY (name) VALUES ('상의');
INSERT INTO CATEGORY (name) VALUES ('아우터');
INSERT INTO CATEGORY (name) VALUES ('바지');
INSERT INTO CATEGORY (name) VALUES ('스니커즈');
INSERT INTO CATEGORY (name) VALUES ('가방');
INSERT INTO CATEGORY (name) VALUES ('모자');
INSERT INTO CATEGORY (name) VALUES ('양말');
INSERT INTO CATEGORY (name) VALUES ('액세서리');
-- A
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,1,'A상의',11200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,2,'A아우터',5500);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,3,'A바지',4200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,4,'A스니커즈',9000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,5,'A가방',2000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,6,'A모자',1700);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,7,'A양말',1800);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (1,8,'A액세서리',2300);
-- B
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,1,'B상의',10500);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,2,'B아우터',5900);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,3,'B바지',3800);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,4,'B스니커즈',9100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,5,'B가방',2100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,6,'B모자',2000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,7,'B양말',2000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (2,8,'B액세서리',2200);
-- C
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,1,'C상의',10000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,2,'C아우터',6200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,3,'C바지',3300);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,4,'C스니커즈',9200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,5,'C가방',2200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,6,'C모자',1900);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,7,'C양말',2200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (3,8,'C액세서리',2100);
-- D
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,1,'D상의',10100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,2,'D아우터',5100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,3,'D바지',3000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,4,'D스니커즈',9500);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,5,'D가방',2500);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,6,'D모자',1500);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,7,'D양말',2400);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (4,8,'D액세서리',2000);
-- E
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,1,'E상의',10700);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,2,'E아우터',5000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,3,'E바지',3800);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,4,'E스니커즈',9900);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,5,'E가방',2300);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,6,'E모자',1800);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,7,'E양말',2100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (5,8,'E액세서리',2100);
-- F
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,1,'F상의',11200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,2,'F아우터',7200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,3,'F바지',4000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,4,'F스니커즈',9300);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,5,'F가방',2100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,6,'F모자',1600);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,7,'F양말',2300);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (6,8,'F액세서리',1900);
-- G
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,1,'G상의',10500);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,2,'G아우터',5800);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,3,'G바지',3900);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,4,'G스니커즈',9000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,5,'G가방',2200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,6,'G모자',1700);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,7,'G양말',2100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (7,8,'G액세서리',2000);
-- H
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,1,'H상의',10800);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,2,'H아우터',6300);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,3,'H바지',3100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,4,'H스니커즈',9700);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,5,'H가방',2100);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,6,'H모자',1600);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,7,'H양말',2000);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (8,8,'H액세서리',2000);
-- I
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,1,'I상의',11400);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,2,'I아우터',6700);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,3,'I바지',3200);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,4,'I스니커즈',9500);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,5,'I가방',2400);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,6,'I모자',1700);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,7,'I양말',1700);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, NAME, PRICE) VALUES (9,8,'I액세서리',2400);